#  /*
#    Copyright © 2023. Cloud Software Group, Inc.
#    This file is subject to the license terms contained
#    in the license file that is distributed with this file.
# */
{{- if .Values.tibotelcollectorfinops.enabled -}}
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: {{ .Values.tibotelcollectorfinops.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    platform.tibco.com/workload-type: "infra"
    platform.tibco.com/dataplane-id: {{ .Values.global.cp.dataplaneId }}
    platform.tibco.com/capability-instance-id: {{ .Values.global.cp.instanceId }}
spec:
  mode: "{{ .Values.tibotelcollectorfinops.mode }}"
  ports:
  {{- range $key, $port := .Values.tibotelcollectorfinops.ports }}
  {{- if $port.enabled }}
    - name: {{ $key }}
      targetPort: {{ $port.targetPort }}
      port: {{ $port.port }}
      protocol: {{ $port.protocol }}
  {{- end }}
  {{- end }}
  config: |
{{- if .Values.tibotelcollectorfinops.config }}
{{ .Values.tibotelcollectorfinops.config | indent 4 }}
{{- else }}
{{ tpl (.Files.Get "config/tibco-otel-collector-finops.yaml") . | indent 4 }}
{{- end }}
{{- end }}