## CONTEXT

replicaCount: "1"
global:
  LOG_LEVEL: debug
  serviceAccountName: "monitor-agent-sa"
  cp: 
    dataplaneId: "abcd"
    subscriptionId: "sub1"
    instanceId: "qwerty"
    containerRegistry:
      url: "reldocker.tibco.com"
  # .Values.global.enableLogging variable can be set to false to disable starting fluentbit side-car containers
  enableLogging: true
enableIngress: true
ingress:
  annotations: {}
    # nginx custom annotation example
    #nginx.org/rewrites: "serviceName={{ include \"tp-dp-monitor-agent.consts.appName\" . }} rewrite=/" #https://github.com/nginxinc/kubernetes-ingress/tree/v2.4.2/examples/ingress-resources/rewrites
  pathPrefix: /tibco/agent/infra/tp-dp-monitor-agent/
  className: "haproxy-dp-{{ .Values.global.cp.dataplaneId}}"  # Ex: nginx, haproxy