# Example helm deployment
global: 
  cp: 
    dataplaneId: 
    instanceId: 

dp:
  serviceAccount: provisioner-agent
  # registry: "664529841144.dkr.ecr.us-west-2.amazonaws.com/"
  # repo: "msg-platform-cicd/"
  # pullSecret: 
  pullSecret: "cic2-tcm-ghcr-secret"
  registry: "ghcr.io/"
  repo: "tibco/msg-platform-cicd/"

ems:
  stores: ftl
  sizing: small
  use: dev
  ports:
    httpPort: 9010
    tcpPort: 9011
    sslPort: 9012
    realmPort: 9013
    adminPort: 9014
    promServerEP: 9091
    promQueuesEP: 9092
    promTopicsEP: 9093
    # FIXME: Are these 2 DP or EMS settings
    watchdogPort: 12502
    loggerPort: 12506
  msgData: 
    storageType: emptyDir
    storageName: none
  logs: 
    storageType: useMsgData
    storageName: none
