{{ if ne (include "dp-core-infrastructure-config.consts.imageCredential" .) "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.tibco.dataPlaneId }}
  labels:
  {{- include "dp-core-infrastructure-config.shared.labels.standard" . | nindent 4}}
    platform.tibco.com/dp-secret-controller: {{ .Values.global.tibco.dataPlaneId }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "dp-core-infrastructure-config.consts.imageCredential" . }}
{{- end }}