{{- if eq .Release.Namespace .Values.global.tibco.primaryNamespaceName -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dp-configure-namespace.dataPlaneId" . }}-cluster-scope
  labels:
    {{- include "dp-configure-namespace.labels" . | nindent 4 }}
rules:
# required by otel collector
# required by istio for discover and routing
- apiGroups: [""]
  resources: ["nodes", "nodes/spec", "nodes/stats", "nodes/proxy"]
  verbs: ["get", "list", "watch"]
# required by otel collector
# required by istio for discover and routing
- apiGroups: [""]
  resources: ["namespaces", "namespaces/status"]
  verbs: ["get", "list", "watch"]
# required by istio for CA's namespace controller
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "get", "list", "watch", "update"]
# required by istio for discover and routing
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]
# required by otel collector
- apiGroups: [""]
  resources: ["resourcequotas"]
  verbs: ["get", "list", "watch"]
# required by otel collector
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]
# required by istio for discover and routing
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
# required by istio for discover and routing
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
# required by otel collector
# required by istio for discover and routing
- apiGroups: [""]
  resources: ["replicationcontrollers", "replicationcontrollers/status"]
  verbs: ["get", "list", "watch"]
# question: can BW list namespaces first by label and then get deployment?
# required for monitoring agent
# required by otel collector
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "statefulsets"]
  verbs: ["get", "list", "watch"]
# required by otel collector
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch"]
# required by otel collector
# required by istio for discovery and routing
- apiGroups: [""]
  resources: ["pods", "pods/status"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["ingresses", "ingressclasses"]
  verbs: ["get", "list", "watch"]
# required by istio
- apiGroups: ["gateway.networking.k8s.io", "networking.x-k8s.io"]
  resources: ["gateways", "gatewayclasses", "httproutes", "tlsroutes", "tcproutes", "udproutes", "backendpolicies"]
  verbs: ["get", "list", "watch"]
# write permissions are required for following
# required by distributed lock operator for CRD creation
# required by istio for installed CRD definitions auto-detect
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create", "get", "list", "watch", "delete", "patch", "update"]
# required by istio for webhook controller
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["validatingwebhookconfigurations"]
  verbs: ["create", "get", "list", "watch", "delete", "patch", "update"]
# required by istio for sidecar injection controller
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["ingresses/status"]
  verbs: ["update"]
# required by istio
- apiGroups: ["config.istio.io", "security.istio.io", "networking.istio.io", "authentication.istio.io", "rbac.istio.io", "telemetry.istio.io", "extensions.istio.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "update"]
# required by istio
- apiGroups: ["networking.istio.io"]
  resources: ["workloadentries", "workloadentries/status"]
  verbs: ["create", "get", "list", "watch", "delete","patch", "update"]
# required by istio
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["get", "list", "watch"]
# required by istio to verify the JWT tokens
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]
# required by istio to verify gateway SDS
- apiGroups: ["authorization.k8s.io"]
  resources: ["subjectaccessreviews"]
  verbs: ["create"]
# required by istio
- apiGroups: ["multicluster.x-k8s.io"]
  resources: ["serviceexports"]
  verbs: ["create", "get", "list", "watch", "delete"]
# required by istio
- apiGroups: ["multicluster.x-k8s.io"]
  resources: ["serviceimports"]
  verbs: ["get", "list", "watch"]
# required by istio
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get", "list", "watch"]

--- 

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dp-configure-namespace.dataPlaneId" . }}-ns-scope
  labels:
    {{- include "dp-configure-namespace.labels" . | nindent 4 }}
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete", "patch", "update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete", "patch", "update"]
# required for getting pod logs for user-apps
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list", "watch"]
# required for getting replicasets of user-apps
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get", "list", "watch"]
# delete required by istio for deletion of distribution report configmap
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "delete", "patch", "update", "delete"]
# required by istio for storing CA secret
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "delete", "patch", "update"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
# required by HA proxy
# required by distributed lock operators
# required by istio for gateway deployment controller
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "create", "update"]
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  resourceNames: ["dp-core-infrastructure-haproxy-ingress"]
  verbs: ["use"]
- apiGroups: ["cloud.tibco.com"]
  resources: ["tibcodistributedlocks", "tibcodistributedlocks/status"]
  verbs: ["create", "get", "list", "watch", "delete", "patch", "update"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["create", "get", "list", "update"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["create", "get", "list", "delete", "update"]
- apiGroups: ["cert-manager.io"]
  resources: ["certificates","issuers"]
  verbs: ["create", "get"]
# required by istio for permissions to verify the webhook is ready and rejecting
- apiGroups: ["networking.istio.io"]
  verbs: ["create"]
  resources: ["gateways"]
{{- end -}}
