{{- if eq .Release.Namespace .Values.global.tibco.primaryNamespaceName -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dp-configure-namespace.dataplaneId" . }}
  labels:
    {{- include "dp-configure-namespace.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dp-configure-namespace.dataplaneId" . }}-cluster-scope
subjects:
  - kind: ServiceAccount
    name: {{ include "dp-configure-namespace.serviceAccount" . }}
    namespace: {{ include "dp-configure-namespace.primaryNamespaceName" . }}
{{- end -}}