{{- if eq .Release.Namespace .Values.global.tibco.primaryNamespaceName -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dp-configure-namespace.dataPlaneId" . }}
  labels:
    {{- include "dp-configure-namespace.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dp-configure-namespace.dataPlaneId" . }}-cluster-scope
subjects:
  - kind: ServiceAccount
    name: {{ include "dp-configure-namespace.serviceAccount" . }}
    namespace: {{ include "dp-configure-namespace.primaryNamespaceName" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dp-configure-namespace.dataPlaneId" . }}-istio-runtime-clusterrole
  labels:
    app: istiod
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dp-configure-namespace.dataPlaneId" . }}-cluster-scope
subjects:
  - kind: ServiceAccount
    name: {{ include "dp-configure-namespace.serviceAccount" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dp-configure-namespace.dataPlaneId" . }}-istio-reader-clusterrole
  labels:
    app: istio-reader
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dp-configure-namespace.dataPlaneId" . }}-reader-cluster-scope
subjects:
  - kind: ServiceAccount
    name: {{ include "dp-configure-namespace.serviceAccount" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
