apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "dp-configure-namespace.dataplaneId" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dp-configure-namespace.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dp-configure-namespace.dataplaneId" . }}-ns-scope
subjects:
- kind: ServiceAccount
  name: {{ include "dp-configure-namespace.serviceAccount" . }}
  namespace: {{ include "dp-configure-namespace.primaryNamespaceName" . }}
