{{- if eq .Release.Namespace .Values.global.tibco.primaryNamespaceName -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "dp-configure-namespace.dataPlaneId" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dp-configure-namespace.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dp-configure-namespace.dataPlaneId" . }}-ns-scope
subjects:
- kind: ServiceAccount
  name: {{ include "dp-configure-namespace.serviceAccount" . }}
  namespace: {{ include "dp-configure-namespace.primaryNamespaceName" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "dp-configure-namespace.dataPlaneId" . }}-istio-role
  namespace: {{ .Release.Namespace }}
  labels:
    app: istiod
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "dp-configure-namespace.dataPlaneId" . }}-ns-scope
subjects:
  - kind: ServiceAccount
    name: {{ include "dp-configure-namespace.serviceAccount" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
