apiVersion: v2
name: dp-configure-namespace
description: A Helm chart for creating service account, cluster-role, cluster-role-binding, role-binding & network-policies
type: application
version: 1.0.7
appVersion: "1.0.7"
