global:
  tibco:
    subscriptionId: "sub1"
    dataplaneId: "abcd"
    # Provide the name of primary namespace where dp-core-infrastrcuture is to be deployed
    # This namespace has the service account for which the role-bindig will be created for primary namespace and additional namespaces
    primaryNamespaceName: "dp-namespace"
    # Provide the name of the service account from primary namespace 
    # This will be used for dp-core-infrastrcuture, capability provisioning, application deployment
    serviceAccount: "sa" 

# Use an already existing service account present in the primary namespace
createServiceAccount: true

# Flag to enable or disable default network policies for a namespace
createNetworkPolicy: true
# Capture any additional network policies to be created for a namespace
additionalNetworkPolicy: {}