apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-tibtunnel
  labels:
    {{- include "tp-tibtunnel.shared.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tp-tibtunnel.shared.labels.selector" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tp-tibtunnel.shared.labels.standard" . | nindent 8 }}
    spec:
      containers:
      - name: tibtunnel
        image: {{ include "tp-tibtunnel.image.registry" .}}{{"/"}}{{ include "tp-tibtunnel.image.repository" .}}{{"/"}}{{ .Values.image.name }}:{{ .Values.image.tag}}
        {{/* Converting the command from "" to ["",""]. Split input command by space and coverting it into array of string */}}
        {{/* @input: "tp-tibtunnel connect --remote-debug -s localhost:80 connecturl" */}}
        {{/* @output: ["tp-tibtunnel", "connect", "--remote-debug","-s","localhost:80","connecturl"] */}}
        command: [{{- range $v := (mustRegexSplit " +" (include "tp-tibtunnel.helpers.command.connect" .) -1) -}}"{{- $v -}}",{{- end -}}]
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10}}
        {{- end }}
        volumeMounts:
        - name: config-dir
          mountPath: /etc/config
{{- if .Values.enableLogging }}
      - name: fluentbit
        image: {{ .Values.fluentbit.image.registry }}:{{ .Values.fluentbit.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid
          - name: CONTAINER_NAME
            value: tibtunnel
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        volumeMounts:
          - name: podlogs
            mountPath: /var/log/pods
          - name: dockercontainerlogs
            mountPath: /var/lib/docker/containers
          - name: config-volume
            mountPath: /fluent-bit/etc/
{{- end }}
      initContainers:
      - name: tibtunnel-init
        image: {{ include "tp-tibtunnel.image.registry" .}}{{"/"}}{{ include "tp-tibtunnel.image.repository" .}}{{"/"}}{{ .Values.image.name }}:{{ .Values.image.tag}}
        command: [{{- range $v := (mustRegexSplit " +" (include "tp-tibtunnel.helpers.command.configure" .) -1) -}}"{{- $v -}}",{{- end -}}]
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10}}
        {{- end }}
        volumeMounts:
        - name: config-dir
          mountPath: /etc/config
      imagePullSecrets:
        {{- if .Values.global.tibco.containerRegistry.username }}{{if .Values.global.tibco.containerRegistry.password }}
        - name: {{ .Values.global.tibco.dataPlaneId }} {{/* optional imagePullSecret for private repo. no op if secret does not exist */}}
        {{- end }}{{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config-dir
          emptyDir: {}
{{- if .Values.enableLogging }}
        - name: podlogs
          hostPath:
            path: /var/log/pods
            type: Directory
        - name: dockercontainerlogs
          hostPath:
            path: /var/lib/docker/containers
            type: DirectoryOrCreate
        - name: config-volume
          configMap:
            name: tp-tibtunnel-fluentbit-config
{{- end }}
