apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    name: {{ include "tp-tibtunnel.consts.appName" . }}
    labels:
        {{- include "tp-tibtunnel.shared.labels.standard" . | nindent 8 }}
spec:
    podSelector:
        matchLabels:
            {{- include "tp-tibtunnel.shared.labels.selector" . | nindent 12 }}
    policyTypes:
        - Egress
    egress:
      - to:
          - ipBlock:
              cidr: 0.0.0.0/0