apiVersion: v1
data:
  ACCESS_KEY: {{ .Values.configure.accessKey | b64enc }}
kind: Secret
metadata:
  annotations:
    "helm.sh/hook": pre-install
  labels:
    {{- include "tp-tibtunnel.shared.labels.standard" . | nindent 4 }}
  name: {{ include "tp-tibtunnel.consts.appName" .}}
  namespace: {{ .Release.Namespace }}
type: Opaque
