{{/* 
   Copyright (c) 2023. Cloud Software Group, Inc. All Rights Reserved. Confidential & Proprietary.

   File       : _generated.tpl
   Version    : 1.0.0
   Description: Template helpers defining generated values for this chart.
   
    NOTES: 
      - This file will be generated by the build server. DO NOT EDIT!
*/}}

{{/* The build number, also used as docker image image tag */}}
{{- define "tp-dp-monitor-agent.generated.buildNumber" }}latest{{ end -}}
