replicaCount: 1

global:
  istioNamespace: istio-system

service:
  type: LoadBalancer
  ports:
  - name: tcp-status
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: http2
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: tcp-sql
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: tcp-opensearch
    port: 5601
    protocol: TCP
    targetPort: 5601
  - name: tcp-ftl
    port: 8085
    protocol: TCP
    targetPort: 8085

tolerations:
  - key: dedicated
    operator: Equal
    value: apim
    effect: NoSchedule

