{{- $root := . }}
{{- if .Values.namespaces }}
{{- range $ns_name, $ns_object := .Values.namespaces }}
{{- if $ns_object.createBinding }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "dp-core-rbac.roleBindingNamePrefix" $root }}-1
  namespace: {{ $ns_name }}
  labels:
    {{- include "dp-core-rbac.labels" $root | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dp-core-rbac.clusterRoleNamePrefix" $root }}-2
subjects:
- kind: ServiceAccount
  name: {{ $root.Values.global.tibco.serviceAccount }}
  namespace: {{ $root.Release.Namespace }}
{{- end }}
{{- end }}
{{- end }}