{{- $root := . }}
{{- if .Values.namespaces }}
{{- range $ns_name, $ns_object := .Values.namespaces }}
{{- if $ns_object.createBinding }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "dp-core-rbac.roleBindingName" $root }}
  namespace: {{ $ns_name }}
  labels:
    {{- include "dp-core-rbac.labels" $root | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dp-core-rbac.clusterRoleName" $root }}-ns-scope
subjects:
- kind: ServiceAccount
  name: {{ $root.Values.global.tibco.serviceAccount }}
  {{- if eq $root.Values.dataplaneNamespaceName "" }}
  namespace: {{ $root.Release.Namespace }}
  {{- else }}
  namespace: {{ $root.Values.dataplaneNamespaceName }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}