apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-cp-proxy
  namespace: {{ .Release.Namespace}}
  labels:
    {{- include "tp-cp-proxy.shared.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tp-cp-proxy.shared.labels.selector" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tp-cp-proxy.shared.labels.standard" . | nindent 8 }}
    spec:
      containers:
      - name: cp-proxy
        image: {{ include "tp-cp-proxy.image.registry" .}}{{"/"}}{{ include "tp-cp-proxy.image.repository" .}}{{"/"}}{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: clientId
                name: {{ include "tp-cp-proxy.consts.outputSecretName" . }}
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                key: clientSecret
                name: {{ include "tp-cp-proxy.consts.outputSecretName" . }}
          - name: DATAPLANE_ID
            value: {{ .Values.global.cp.dataplaneId }}
          - name: NAMESPACE
            value: {{ .Release.Namespace }}
        args:
          - start
          - -o
          - "https://{{ .Values.global.cp.cpHostName }}"
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10}}
        {{- end }}
        ports:
        - containerPort: 3125
          name: proxy
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      imagePullSecrets:
        - name: {{ .Values.global.cp.containerRegistry.secret }} {{/* optional imagePullSecret for private repo. no op if secret does not exist */}}
