{{ if eq .Values.global.cp.resources.serviceAccount.serviceAccountName "" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tp-cp-proxy.consts.appName" .}}-job-sa
  labels:
    {{- include "tp-cp-proxy.shared.labels.standard" . | nindent 4 }}
{{ end }}