{{- $fullName := include "bwprovisioner.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bwprovisioner.fullname" . }}
  labels:
    {{- include "bwprovisioner.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bwprovisioner.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 1
    type: RollingUpdate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bwprovisioner.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.global.cp.containerRegistry.secret }}
      {{- if .Values.global.cp.resources.serviceaccount.serviceAccountName }}
      serviceAccountName: {{ .Values.global.cp.resources.serviceaccount.serviceAccountName }}
      {{- else }}
      serviceAccountName: {{ include "bwprovisioner.sa" . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: server
            - containerPort: {{ .Values.publicApiService.port }}
              name: publicapiserver
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "bwprovisioner.image.registry" .}}{{"/"}}{{ include "bwprovisioner.image.repository" .}}{{"/"}}bw-provisioner:{{ .Values.global.bwprovisioner.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: v1/liveness
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- range $filename, $content :=  .Values.config }}
            {{- if $content }}
            - name: {{ $filename }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $fullName }}-serviceconfig
                  key: {{ $filename }}
            {{- end }}
            {{- end }}
            - name: DATAPLANE_ID
              value: {{ .Values.global.cp.dataplaneId }}
            - name: INSTANCE_ID
              value: {{ .Values.global.cp.instanceId }}
            - name: BW_PROVISIONER_BUILD
              value: "{{ .Values.global.bwprovisioner.image.tag }}"
            - name: SERVER_PORT
              value: "{{ .Values.service.port }}"
            - name: PUBLIC_API_SERVER_PORT
              value: "{{ .Values.publicApiService.port }}"
            - name: CP_DOMAIN
              value: {{ include "bwprovisioner.cp.domain" . }}
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: IMAGE_PULL_SECRET
              value: {{ .Values.global.cp.containerRegistry.secret }}
            - name: APP_INIT_SOURCE_REGISTRY
              value: {{ include "bwprovisioner.image.registry" .}}{{"/"}}{{ include "bwprovisioner.appinit.image.repository" .}}{{"/"}}
            - name: SOURCE_REGISTRY
              value: {{ include "bwprovisioner.image.registry" .}}{{"/"}}{{ include "bwprovisioner.image.repository" .}}{{"/"}}
#            - name: OTEL_SERVICE_NAME
#              valueFrom:
#                configMapKeyRef:
#                  name: {{ include "bwprovisioner.o11yservice.configmap" . }}
#                  key: otel-recvservice-name
#            - name: OTEL_SERVICE_PORT
#              valueFrom:
#                configMapKeyRef:
#                  name: {{ include "bwprovisioner.o11yservice.configmap" . }}
#                  key: otel-recvservice-port
        {{- if .Values.global.bwprovisioner.logging.enabled }}
        - name: fluent-bit
          image: {{ .Values.global.bwprovisioner.logging.image.registry }}fluent-bit:{{ .Values.global.bwprovisioner.logging.image.tag }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          resources:
            {{- toYaml .Values.global.bwprovisioner.deploymanager.resources | nindent 12 }}
          securityContext:
            privileged: true
          ports:
            - containerPort: 2020
          env:
            - name: ACCOUNT_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-serviceconfig
                  key: SERVICE_LOGSERVER_HOST
            - name: SERVICE_LOGSERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-serviceconfig
                  key: SERVICE_LOGSERVER_HOST

            - name: SERVICE_LOGSERVER_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-serviceconfig
                  key: SERVICE_LOGSERVER_USER

            - name: LOGSERVER_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-serviceconfig
                  key: LOGSERVER_PASSWORD

            - name: SERVICE_LOGSERVER_INDEX
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-serviceconfig
                  key: SERVICE_LOGSERVER_INDEX

            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TIBCO_INTERNAL_INTERCOM_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-{{ .Chart.Name }}-serviceconfig
                  key: TIBCO_INTERNAL_INTERCOM_URL
            - name: POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: CONTAINER_NAME
              value: {{ .Chart.Name }}

          volumeMounts:
            - name: dockercontainerlogs
              mountPath: /var/lib/docker/containers/
            - name: podlogs
              mountPath: /var/log/pods
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
        terminationGracePeriodSeconds: 10
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.global.bwprovisioner.logging.enabled }}
      volumes:
        - name: dockercontainerlogs
            hostPath:
              path: /var/lib/docker/containers/
        - name: podlogs
          hostPath:
            path: /var/log/pods
        - name: fluent-bit-config
          configMap:
            name: {{ include "bwprovisioner.fluentConf" . }}
      {{- end }}
