apiVersion: cloud.tibco.com/v1
kind: TibcoAlb
metadata:
  name: {{ .Values.ingressProvider.name }}-ingress-external
  namespace: {{ .Release.Namespace }}
spec:
  profileName: lb-external
  endpoint:
    healthCheckSetting:
      checkConfig:
        healthyThreshold: 2
        interval: 20
        timeout: 5
        unhealthyThreshold: 2
      healthCheckPath: /ping
      healthCheckPort: 9000
      healthCheckSuccessCodes: "404"
    lbPort: 443
    lbProtocol: HTTPS
    path: /*
    targetPort: {{ .Values.ingressProvider.port }}
    targetProtocol: HTTPS
  serviceName: {{ .Release.Name }}{{ .Values.ingressProvider.serviceNameSuffix }}
---

apiVersion: cloud.tibco.com/v1
kind: TibcoDns
metadata:
  name: {{ .Values.ingressProvider.name }}-ingress-external
  namespace: {{ .Release.Namespace }}
spec:
  dns:
    domain: {{ .Values.domain.external }}
    vanityDomain: "*"
  values:
    crRef:
      crKind: tibcoalb
      name: {{ .Values.ingressProvider.name }}-ingress-external
      namespace: {{ .Release.Namespace }}
