{{- if .Values.storageClass.ebs.enabled  -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.ebs.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "{{ .Values.storageClass.ebs.default }}"
parameters:
{{- range $key, $value := .Values.storageClass.ebs.parameters }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
provisioner: ebs.csi.aws.com
reclaimPolicy: {{ .Values.storageClass.ebs.reclaimPolicy }}
allowVolumeExpansion: {{ .Values.storageClass.ebs.allowVolumeExpansion }}
volumeBindingMode: {{ .Values.storageClass.ebs.volumeBindingMode }}
{{- end -}}
