receivers:
  kubeletstats:
    collection_interval: 20s
    auth_type: "serviceAccount"
    endpoint: {{ .Values.kubeletstats.kubeletEndpoint }}
    insecure_skip_verify: true
    metric_groups:
    - pod   
    extra_metadata_labels:
      - container.id
    metrics:
      k8s.pod.filesystem.available:
        enabled: false
      k8s.pod.filesystem.capacity:
        enabled: false
      k8s.pod.filesystem.usage:
        enabled: false
      k8s.pod.memory.major_page_faults:
        enabled: false
      k8s.pod.memory.page_faults:
        enabled: false
      k8s.pod.memory.rss:
        enabled: false
      k8s.pod.memory.working_set:
        enabled: false
processors:
  batch:
    send_batch_size: 10000
    timeout: 200ms
  k8sattributes:
    auth_type: "serviceAccount"
    extract:
      metadata:
        - k8s.pod.name
        - k8s.pod.uid
        - k8s.deployment.name
        - k8s.container.name
        - k8s.namespace.name
        - k8s.node.name
        - k8s.pod.start_time
      annotations:
        - key_regex: .* # extracts Keys & values of annotations matching regex `*`
          from: pod
      labels:
        - key_regex: .* # extracts Keys & values of labels matching regex `*`
          from: pod
    pod_association:
      - sources:
          - from: resource_attribute
            name: k8s.pod.uid
  transform:
    metric_statements:
    - context: datapoint
      statements:
        - set(attributes["k8s_namespace_name"], resource.attributes["k8s.namespace.name"])
        - set(attributes["k8s_container_name"], resource.attributes["k8s.container.name"])
        - set(attributes["k8s_pod_name"], resource.attributes["k8s.pod.name"])
        - set(attributes["k8s_deployment_name"], resource.attributes["k8s.deployment.name"])

exporters:
  logging: {}
  file:
    path: ./data/filename_metrics.json
  prometheusremotewrite:
    endpoint: "{{ .Values.kubeletstats.prometheusEndpoint }}"
    headers:
      Authorization: "Bearer {{ .Values.kubeletstats.prometheusToken}}"
    timeout: 20s
service:
  telemetry:
    logs:
      level: "info"
    metrics:
      level: basic
      address: 0.0.0.0:8888
  pipelines:
    metrics:
      exporters:
        - prometheusremotewrite
        - file
      processors:
        - k8sattributes
        - transform
        - batch
      receivers:
        - kubeletstats