exporters:
  logging: {}
  prometheus:
    endpoint: 0.0.0.0:4319
    enable_open_metrics: true
    resource_to_telemetry_conversion:
      enabled: true
  prometheusremotewrite:
    endpoint: "{{ .Values.metricscollector.prometheusEndpoint }}"
    headers:
      Authorization: "Bearer {{ .Values.metricscollector.prometheusToken}}"
    external_labels:
      server: otel-metric-collector
extensions:
  health_check: {}
  memory_ballast:
processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 2000
  batch: {}
receivers:
  fluentforward:
    endpoint: 0.0.0.0:8006
  jaeger:
    protocols:
      grpc:
        endpoint: "{{ .Values.metricscollector.jaegerGRPCEndpoint }}"
      thrift_compact:
        endpoint: "{{ .Values.metricscollector.jaegerThriftCompactEndpoint }}"
      thrift_http:
        endpoint: "{{ .Values.metricscollector.jaegerThriftHttpEndpoint }}"
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        cors:
          allowed_origins:
            - http://*
            - https://*
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: otel-collector
          scrape_interval: 10s
          static_configs:
            - targets: ['0.0.0.0:8888']
        - job_name: k8s
          kubernetes_sd_configs:
          - role: pod
          metric_relabel_configs:
          - action: keep
            regex: (request_duration_seconds.*|response_duration_seconds.*)
            source_labels:
            - __name__
          relabel_configs:
          - action: keep
            regex: "true"
            source_labels:
            - __meta_kubernetes_pod_annotation_prometheus_io_scrape
  zipkin:
    endpoint: "{{ .Values.metricscollector.zipkinEndpoint }}"
service:
  telemetry:
    logs: {}
    metrics:
      address: :8888
  extensions:
    - health_check
    - memory_ballast
  pipelines:
    logs:
      exporters:
        - logging
      processors:
        - memory_limiter
        - batch
      receivers:
        - otlp
    metrics:
      exporters:
        - logging
        - prometheusremotewrite
      processors:
        - memory_limiter
        - batch
      receivers:
        - otlp
        - prometheus
    traces:
      exporters:
        - logging
      processors:
        - memory_limiter
        - batch
      receivers:
        - otlp
        - jaeger
        - zipkin
