{{- if eq .Values.tls.setup "production" -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cic-cert-subscription-scope-production
  namespace: tibco-system
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: cloud@tibco.com
    privateKeySecretRef:
      name: cic-cert-subscription-scope-production
    solvers:
      - dns01:
          azureDNS:
            hostedZoneName: "{{ .Values.global.dnsSandboxSubdomain }}.{{ .Values.global.dnsGlobalTopDomain }}"
            resourceGroupName: "{{ .Values.global.azureSubscriptionDnsResourceGroup }}"
            subscriptionID: "{{ .Values.global.azureSubscriptionId }}"
            environment: AzurePublicCloud
            managedIdentity:
              clientID: "{{ .Values.global.azureAwiAsoDnsClientId }}"

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cic-certificate-production
  namespace: {{ .Values.tls.certificateNamespace }}
spec:
  secretName: {{ .Values.tls.certificateSecretName }}
  issuerRef:
    name: cic-cert-subscription-scope-production
    kind: ClusterIssuer
  dnsNames:
  - '*.{{ .Values.global.azureResourceGroup }}.{{ .Values.global.dnsSandboxSubdomain }}.{{ .Values.global.dnsGlobalTopDomain }}'

{{- end }}
