apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "ingress-nginx.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
    {{- with .Values.ingress-nginx.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- if .Values.ingress-nginx.configAnnotations }}
  annotations: {{ toYaml .Values.ingress-nginx.configAnnotations | nindent 4 }}
{{- end }}
  name: {{ include "ingress-nginx.ingress-nginx.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  use-forwarded-headers: "{{ .Values.ingress-nginx.useforwardedheaders }}"
  allow-snippet-annotations: "{{ .Values.controller.allowSnippetAnnotations }}"