{{- if .Values.storageClass.azurefile.enabled -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.azurefile.name }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "{{ .Values.storageClass.azurefile.default }}"
provisioner: file.csi.azure.com
reclaimPolicy: {{ .Values.storageClass.azurefile.reclaimPolicy }}
allowVolumeExpansion: {{ .Values.storageClass.azurefile.allowVolumeExpansion }}
volumeBindingMode: {{ .Values.storageClass.azurefile.volumeBindingMode }}
parameters:
{{- range $key, $value := .Values.storageClass.azurefile.parameters }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end -}}