#  /*
#    Copyright © 2023. Cloud Software Group, Inc.
#    This file is subject to the license terms contained
#    in the license file that is distributed with this file.
# */
apiVersion: v2
name: dp-otel-collectors
version: "1.0.14"
appVersion: "1.0.0"
description: Collections of OpenTelemetry Collector CRs
type: application
home: https://github.com/tibco/cicinfra-integration
maintainers:
  - name: TIBCO Cloud Dev Team
    email: cloud@tibco.com
