{{- if .Values.enableIngress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "tp-provisioner-agent.consts.appName" . }}
  namespace: {{ .Release.Namespace}}
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    {{- with .Values.ingress.annotations }}
    {{- tpl (toYaml .) $ | nindent 4}}
    {{- end }}
spec:
  ingressClassName: {{ tpl .Values.ingress.className . }}
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: {{ .Values.ingress.pathPrefix }}
        backend:
          service:
            name: {{ include "tp-provisioner-agent.consts.appName" . }}
            port:
              number: 80
    {{- with .Values.ingress.host }}
    host: {{ . }}
    {{- end }}
{{- end }}