# Copyright © 2023. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

apiVersion: v1
kind: Service
metadata:
  name: {{ include "tp-provisioner-agent.consts.appName" . }}
  namespace: {{ .Release.Namespace}}
  labels:
    {{- include "tp-provisioner-agent.shared.labels.standard" . | nindent 4 }}
spec:
  selector:
    {{- include "tp-provisioner-agent.shared.labels.selector" . | nindent 4 }}
  ports:
  - name: provisioner
    port: 80
    protocol: TCP
    targetPort: provisioner
  sessionAffinity: None
  type: ClusterIP