apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-cp-proxy
  namespace: {{ .Release.Namespace}}
  labels:
    {{- include "tp-cp-proxy.shared.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tp-cp-proxy.shared.labels.selector" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tp-cp-proxy.shared.labels.standard" . | nindent 8 }}
      annotations:
    spec:
      containers:
      - name: cp-proxy
        image: {{ if .Values.image.registry}}{{ .Values.image.registry }}{{else}}{{ .Values.global.dockerRegistry }}{{end}}{{ .Values.image.repository }}:{{ include "tp-cp-proxy.generated.buildNumber" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: CONTROL_PLANE_URL
            value: {{ .Values.controlPlaneUrl }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10}}
        {{- end }}
        ports:
        - containerPort: 3125
          name: proxy
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}