apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    name: {{ include "tp-cp-proxy.consts.appName" . }}
    namespace: {{ .Release.Namespace}}
    labels:
        {{- include "tp-cp-proxy.shared.labels.standard" . | nindent 8 }}
spec:
    podSelector:
        matchLabels:
            {{- include "tp-cp-proxy.shared.labels.selector" . | nindent 12 }}
    policyTypes:
        - Ingress
        - Egress
    ingress:
      - from:
          - namespaceSelector: {}
            podSelector:
              matchLabels:
                component: kube-apiserver
      - from:
          - namespaceSelector: {}
        ports:
          - protocol: TCP
            port: proxy
    egress:
      - {}