global:
  tibco:
    serviceAccount: "service-account" # customer provided service account
    dataPlaneId: "abcd"

## this creates cluster roles which are not namespaced
clusterRole:
  create: true
  createBinding: true

## this creates namespaces and role-bindings in those namespaces
namespaces:
  # namespacea:
  #   createBinding: true
  #   createNetworkPolicy: true
  # namespaceb:
  #   createBinding: true
  #   createNetworkPolicy: true
  # nsc:
  #   createBinding: true
  #   createNetworkPolicy: true
  nsd:
    createBinding: true
    createNetworkPolicy: true