apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-provisioner-agent
  namespace: {{ .Release.Namespace}}
  labels:
    {{- include "tp-provisioner-agent.shared.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tp-provisioner-agent.shared.labels.selector" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tp-provisioner-agent.shared.labels.standard" . | nindent 8 }}
      annotations:
    spec:
      {{- if .Values.serviceAccount }}
      serviceAccountName: {{ .Values.serviceAccount }}
      {{- else }}
      serviceAccountName: {{ include "tp-provisioner-agent.consts.appName" . }}
      {{- end }}
      containers:
      - name: provisioner-agent
        image: {{ if .Values.image.registry}}{{ .Values.image.registry }}{{else}}{{ .Values.global.dockerRegistry }}{{end}}{{ .Values.image.repository }}:{{ include "tp-provisioner-agent.generated.buildNumber" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10}}
        {{- end }}
        ports:
        - containerPort: 3124
          name: provisioner
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /version
            port: 3124
          failureThreshold: 1
          successThreshold: 1
          timeoutSeconds: 5
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /version
            port: 3124
          failureThreshold: 1
          successThreshold: 1
          timeoutSeconds: 5
          initialDelaySeconds: 10
          periodSeconds: 10
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}