{{- if eq .Values.serviceAccount "" }}

kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "tp-provisioner-agent.consts.appName" . }}
  namespace: {{ .Release.Namespace}}
  labels:
    {{- include "tp-provisioner-agent.shared.labels.standard" . | nindent 4 }}

---
# TODO: add restricted RBACs for provisioner agent
# ResourceSetOperator pod needs access to all the kubernetes resources
# hence cluster role binding for built-in cluster-admin role is created
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "tp-provisioner-agent.consts.appName" . }}-{{ .Values.global.tibcoDataPlaneId }}-crb
  labels:
    {{- include "tp-provisioner-agent.shared.labels.standard" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "cluster-admin"
subjects:
- kind: ServiceAccount
  name: {{ include "tp-provisioner-agent.consts.appName" . }}
  namespace: {{ .Release.Namespace }}

{{- end }}