#revision: "platform"

serviceAccount:
  create: false

pilot:
  autoscaleEnabled: true
  autoscaleMin: 1
  autoscaleMax: 5
  replicaCount: 1
  traceSampling: 100.0

global:
  istioNamespace: tibco-istio
  cp:
    containerRegistry:
      secret: ck5mt5gvnmjhmo7kk21g
      url: 664529841144.dkr.ecr.us-west-2.amazonaws.com
    dataplaneId: "ck5mt5gvnmjhmo7kk21g"
    resources:
      serviceaccount:
        serviceAccountName: istio-dataplane-service-account
  security:
     peerAuthentication: PERMISSIVE
  defaultResources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  defaultPodDisruptionBudget:
    enabled: true
  proxy:
    tracer: "openCensusAgent"

meshConfig:
  accessLogFile: /dev/stdout

  defaultConfig:
    tracing:
      zipkin:
        address: "opentelemetry-collector.tibco-istio.svc.cluster.local:9411"

  extensionProviders:
  - name: opentelemetry
    opentelemetry:
      service: opentelemetry-collector.tibco-istio.svc.cluster.local
      port: 4317