revision: "platform"

serviceAccount:
  create: true
  name: istio-service-account

pilot:
  autoscaleEnabled: true
  autoscaleMin: 1
  autoscaleMax: 5
  replicaCount: 1
  traceSampling: 100.0

global:
  istioNamespace: apim-cic2
  cp:
    resources:
      serviceaccount:
        serviceAccountName: istio-cp-service-account
  security:
     peerAuthentication: PERMISSIVE
  defaultResources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

meshConfig:
  accessLogFile: /dev/stdout

  defaultConfig:
    tracing:
      zipkin:
        address: "opentelemetry-collector.apim-cic2.svc.cluster.local:9411"

  #defaultProviders:
  #  metrics: ["prometheus"]
  #  tracing: ["traceCollector"]
  #  accessLogging: ["logCollector"]

  #extensionProviders:
  #- name: logCollector
  #  envoyOtelAls:
  #    service: opentelemetry-collector.apim-cic2.svc.cluster.local
  #    port: 4318
  #    logName: "istio_envoy_accesslog"
  #- name: traceCollector
  #  opentelemetry:
  #    service: opentelemetry-collector.apim-cic2.svc.cluster.local
  #    port: 4317
  #- name: zipkin
  #  zipkin:
  #    service: opentelemetry-collector.apim-cic2.svc.cluster.local
  #    port: 9411

members:
   dataplane-id: tibco-dp

