{{/* 
    NOTES: 
      - This file will be generated by the build server. DO NOT EDIT!
*/}}

{{/* The build number, also used as docker image image tag */}}
{{- define "tibco-hub.generated.buildNumber" }}latest{{ end -}}