{{- if .Values.global.security.peerAuthentication }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: "{{ .Release.Namespace }}-default-security-policy"
spec:
  mtls:
    mode: "{{ .Values.global.security.peerAuthentication }}"
{{- end }}