apiVersion: v1
appVersion: 1.19.0
description: Helm chart for istio control plane
icon: https://github.com/cncf/artwork/blob/master/projects/istio/icon/color/istio-icon-color.svg
keywords:
- istio
- istiod
- istio-discovery
name: istio-istiod
sources:
- https://github.com/istio/istio
version: 1.0.2
