name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.13.1'

      - name: Configure Tibco Platform repo
        run: |
          helm repo add tibco-platform https://syan-tibco.github.io/tp-helm-charts

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          skip_existing: true
          packages_with_index: false # set to true when https://github.com/helm/chart-releaser/pull/314 is merged for private repo
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
