name: Release Charts

on:
  push:
    branches:
      - main
      - tibco-hub

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.11.1'
      
      - name: Add repositories
        run: |
            helm dependency list 'charts/tibco-hub' 2> /dev/null | tail +2 | head -n 2 | awk '{ print "helm repo add " $1 " " $3 }' | while read cmd; do $cmd; done    

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true
